"""InferMatrixCopilot embedded SDK v1 public surface."""

from .direct import DirectClient, get_capabilities
from .knowledge import KnowledgeCurator, KnowledgeValidatorError
from .models import (
    DIRECT_API_VERSION,
    KNOWLEDGE_API_VERSION,
    SDK_API_VERSION,
    STRICT_API_VERSION,
    Capabilities,
    ChangedPath,
    DirectCompletionDecision,
    DirectCompletionRequest,
    DirectReviewPlan,
    DirectReviewRequest,
    DocumentNotFoundError,
    DocumentPage,
    DocumentRef,
    IncompatibleVersionError,
    InvalidRequestError,
    KnowledgeApplyResult,
    KnowledgeCurationError,
    KnowledgeEvidenceBatch,
    KnowledgeEvidenceEvent,
    KnowledgeProposalRejection,
    KnowledgeProposalValidation,
    KnowledgeRoute,
    KnowledgeRuleProposal,
    KnowledgeValidatorResult,
    RepositoryRef,
    SDKError,
    StrictPollResult,
    StrictReviewRequest,
    StrictRunHandle,
    UnsupportedRepositoryError,
)
from .strict import StrictRuntime

__all__ = [
    "DIRECT_API_VERSION",
    "KNOWLEDGE_API_VERSION",
    "SDK_API_VERSION",
    "STRICT_API_VERSION",
    "Capabilities",
    "ChangedPath",
    "DirectClient",
    "DirectCompletionDecision",
    "DirectCompletionRequest",
    "DirectReviewPlan",
    "DirectReviewRequest",
    "DocumentNotFoundError",
    "DocumentPage",
    "DocumentRef",
    "IncompatibleVersionError",
    "InvalidRequestError",
    "KnowledgeApplyResult",
    "KnowledgeCurationError",
    "KnowledgeCurator",
    "KnowledgeEvidenceBatch",
    "KnowledgeEvidenceEvent",
    "KnowledgeProposalRejection",
    "KnowledgeProposalValidation",
    "KnowledgeRoute",
    "KnowledgeRuleProposal",
    "KnowledgeValidatorError",
    "KnowledgeValidatorResult",
    "RepositoryRef",
    "SDKError",
    "StrictPollResult",
    "StrictReviewRequest",
    "StrictRunHandle",
    "StrictRuntime",
    "UnsupportedRepositoryError",
    "get_capabilities",
]
