# GENERATED by tools/build_kb_gate_bundle.py from src/infermatrix_copilot/knowledge_service/verdict.py -- do not edit here.
"""The kb-gate verdict: what the knowledge service signs and the verifier checks.

A verdict binds a decision to ONE pull request state:

* identity: repository, PR number, exact head SHA, nonce, issue time and a
  72-hour issue window (it must first verify within it);
* the complete patch manifest: every changed path with change type, pre-image
  and post-image git blob IDs and file modes, compared independently of any
  base SHA (so a queued PR is checked against what the queue actually applies);
* the per-block judgements for every rule and prose block L1 produced, the
  change-set consistency judgement with the page hashes it saw, and the
  context base those judgements were made against;
* upstream fact attestations (the verifier re-checks public upstreams);
* who decided: ``auto`` (L1 + L2 + consistency) or ``human-approved`` (with the
  approving review IDs and reviewers).

Standard library only (plus ``signing`` for the envelope): vendored by kb-gate.
"""

from __future__ import annotations

import hashlib
import re
import secrets
from dataclasses import dataclass
from typing import Any, Iterable, Mapping

SCHEMA = "kb-gate-verdict/1"
ISSUE_WINDOW_SECONDS = 72 * 3600
SOURCES = ("auto", "human-approved")
_SHA40 = re.compile(r"[0-9a-f]{40}")


class VerdictError(ValueError):
    """A verdict is malformed or does not match what it claims to cover."""


def git_blob_id(data: bytes | str | None) -> str:
    """The git object ID of a blob with this content ("" for an absent file)."""
    if data is None:
        return ""
    if isinstance(data, str):
        data = data.encode("utf-8")
    return hashlib.sha1(b"blob %d\0" % len(data) + data).hexdigest()


@dataclass(frozen=True)
class ManifestEntry:
    path: str
    status: str        # A | M | D
    old_blob: str
    new_blob: str
    old_mode: str
    new_mode: str

    def to_dict(self) -> dict:
        return {"path": self.path, "status": self.status, "old_blob": self.old_blob,
                "new_blob": self.new_blob, "old_mode": self.old_mode, "new_mode": self.new_mode}


def manifest_from_files(base: Mapping[str, str], head: Mapping[str, str], *,
                        prefix: str = "knowledge/") -> list[dict]:
    """Patch manifest for a change expressed as knowledge-relative text maps."""
    entries = []
    for rel in sorted(set(base) | set(head)):
        before, after = base.get(rel), head.get(rel)
        if before == after:
            continue
        status = "A" if before is None else "D" if after is None else "M"
        entries.append(ManifestEntry(
            path=prefix + rel, status=status,
            old_blob=git_blob_id(before), new_blob=git_blob_id(after),
            old_mode="" if before is None else "100644",
            new_mode="" if after is None else "100644",
        ).to_dict())
    return entries


def canonical_manifest(entries: Iterable[Mapping[str, Any]]) -> list[dict]:
    """Sorted, field-complete manifest; the comparison form (no base SHA)."""
    out = []
    for entry in entries:
        missing = {"path", "status", "old_blob", "new_blob", "old_mode", "new_mode"} - set(entry)
        if missing:
            raise VerdictError(f"manifest entry lacks {sorted(missing)}")
        out.append({key: str(entry[key]) for key in
                    ("path", "status", "old_blob", "new_blob", "old_mode", "new_mode")})
    return sorted(out, key=lambda item: item["path"])


def build_verdict(*, repository: str, pr: int, head_sha: str, context_base_sha: str,
                  manifest: list[dict], blocks: list[dict], consistency: list[dict],
                  release: str, upstream: dict, facts: list[dict], models: dict,
                  source: str = "auto", review_ids: tuple[int, ...] = (),
                  reviewers: tuple[str, ...] = (), issued_at: float) -> dict:
    if source not in SOURCES:
        raise VerdictError(f"source must be one of {SOURCES}")
    if not _SHA40.fullmatch(head_sha) or not _SHA40.fullmatch(context_base_sha):
        raise VerdictError("head_sha and context_base_sha must be 40-character hex SHAs")
    if source == "human-approved" and not (review_ids and reviewers):
        raise VerdictError("a human-approved verdict names its approving reviews")
    for block in blocks:
        if block.get("verdict") != "pass":
            raise VerdictError(f"only passing blocks are signed: {block.get('block_id')}")
    for item in consistency:
        if item.get("verdict") != "consistent":
            raise VerdictError("only a consistent change set is signed")
    return {
        "schema": SCHEMA,
        "repository": repository,
        "pr": int(pr),
        "head_sha": head_sha,
        "context_base_sha": context_base_sha,
        "issued_at": float(issued_at),
        "valid_until": float(issued_at) + ISSUE_WINDOW_SECONDS,
        "nonce": secrets.token_hex(16),
        "source": source,
        "review_ids": [int(value) for value in review_ids],
        "reviewers": list(reviewers),
        "release": release,
        "upstream": upstream,
        "manifest": canonical_manifest(manifest),
        "blocks": sorted(blocks, key=lambda b: b["block_id"]),
        "consistency": consistency,
        "facts": facts,
        "models": models,
    }


def check_binding(verdict: Mapping[str, Any], *, repository: str, pr: int, head_sha: str,
                  now: float) -> None:
    """Identity half of verification: the verdict names THIS PR state and is
    within its issue window. Replaying a verdict on another PR, another head,
    or after the window fails here."""
    if verdict.get("schema") != SCHEMA:
        raise VerdictError("unknown verdict schema")
    if verdict.get("repository") != repository or int(verdict.get("pr", -1)) != int(pr):
        raise VerdictError("verdict is for another repository or pull request")
    if verdict.get("head_sha") != head_sha:
        raise VerdictError("verdict is for another head commit")
    if not float(verdict.get("issued_at", 0)) <= now <= float(verdict.get("valid_until", 0)):
        raise VerdictError("verdict is outside its issue window")
    if verdict.get("source") not in SOURCES:
        raise VerdictError("verdict source is invalid")


def manifests_equal(signed: Iterable[Mapping[str, Any]], actual: Iterable[Mapping[str, Any]]) -> bool:
    return canonical_manifest(signed) == canonical_manifest(actual)
