#!/usr/bin/env python3
"""Generate (or check) the pinned kb-gate verifier bundle in ``.github/kb-gate/``.

The required check ``kb-gate`` runs ONLY from this bundle, never from ``src/``,
``tools/`` or ``knowledge/tools/``: weakening validation logic in a code PR does
not weaken the gate, and changing the bundle is a ``.github/**`` change that
CODEOWNERS must approve. The bundle is a verbatim copy of the verifier modules
with a generated-file header, plus ``requirements.lock`` (dependencies pinned by
hash) and ``MANIFEST.sha256`` (every bundle file's hash).

    python tools/build_kb_gate_bundle.py            # regenerate the module copies + manifest
    python tools/build_kb_gate_bundle.py --check    # exit 1 when the bundle is stale
    python tools/build_kb_gate_bundle.py --lock     # re-pin requirements.lock from PyPI (network)

A stale bundle keeps the gate at its previous strictness; ``--check`` in CI only
reminds that the source moved on.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
import urllib.request
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SOURCE = REPO / "src" / "infermatrix_copilot" / "knowledge_service"
BUNDLE = REPO / ".github" / "kb-gate"
# bundle file -> source module (the verifier imports its siblings by flat name)
MODULES = {
    "kb_gate.py": "gate_verifier.py",
    "l1.py": "l1.py",
    "lifecycle.py": "lifecycle.py",
    "ops.py": "ops.py",
    "signing.py": "signing.py",
    "verdict.py": "verdict.py",
}
# the pinned runtime dependencies: signing needs cryptography (-> cffi ->
# pycparser), l1/lifecycle/ops need PyYAML
PINS = {"cryptography": "50.0.1", "cffi": "2.1.1", "pycparser": "3.0", "PyYAML": "6.0.3"}
STATIC = ("README.md", "config.json", "requirements.lock")
HEADER = "# GENERATED by tools/build_kb_gate_bundle.py from {src} -- do not edit here.\n"


def module_text(bundle_name: str) -> str:
    src = SOURCE / MODULES[bundle_name]
    return HEADER.format(src=src.relative_to(REPO).as_posix()) + src.read_text(encoding="utf-8")


def manifest_text(files: dict[str, str]) -> str:
    return "".join(f"{hashlib.sha256(files[name].encode()).hexdigest()}  {name}\n" for name in sorted(files))


def expected_bundle() -> dict[str, str]:
    files = {name: module_text(name) for name in MODULES}
    for name in STATIC:
        path = BUNDLE / name
        if not path.is_file():
            raise SystemExit(f"{path.relative_to(REPO)} is missing")
        files[name] = path.read_text(encoding="utf-8")
    files["MANIFEST.sha256"] = manifest_text(files)
    return files


def lock_text() -> str:
    lines = ["# GENERATED by tools/build_kb_gate_bundle.py --lock. Install with:",
             "#   pip install --require-hashes --no-deps -r .github/kb-gate/requirements.lock"]
    for name, version in PINS.items():
        with urllib.request.urlopen(f"https://pypi.org/pypi/{name}/{version}/json", timeout=30) as resp:
            data = json.load(resp)
        hashes = sorted({item["digests"]["sha256"] for item in data["urls"]})
        lines.append(f"{name}=={version} \\")
        lines.extend(f"    --hash=sha256:{digest} \\" for digest in hashes[:-1])
        lines.append(f"    --hash=sha256:{hashes[-1]}")
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--lock", action="store_true")
    args = parser.parse_args(argv)
    if args.lock:
        (BUNDLE / "requirements.lock").write_text(lock_text(), encoding="utf-8")
    expected = expected_bundle()
    actual = {p.name: p.read_text(encoding="utf-8") for p in BUNDLE.iterdir() if p.is_file()} \
        if BUNDLE.is_dir() else {}
    stale = sorted(name for name in set(expected) | set(actual) if expected.get(name) != actual.get(name))
    if args.check:
        for name in stale:
            print(f"kb-gate bundle is stale: .github/kb-gate/{name}")
        if stale:
            print("regenerate with: python tools/build_kb_gate_bundle.py (a .github/** change: CODEOWNERS review)")
        return 1 if stale else 0
    BUNDLE.mkdir(parents=True, exist_ok=True)
    for name, text in expected.items():
        (BUNDLE / name).write_text(text, encoding="utf-8")
    for name in set(actual) - set(expected):
        (BUNDLE / name).unlink()
    print(f"kb-gate bundle: {len(expected)} files" + (f", updated {', '.join(stale)}" if stale else ", unchanged"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
