"""The release-sweep summary: findings, fixes, people's queue and cost.

Every settled sweep writes ``<state_dir>/reports/sweep-<repo>-<tag>.md``.
For a repository in auto_merge with a public upstream, the same summary is
also published as one issue in the knowledge repository through the outbox
(``open_issue``); the publisher creates it once, keyed by its title. Shadow
and private repositories publish nothing.
"""

from __future__ import annotations

import json
from collections import Counter

MARKER = "<!-- kb-sweep-report:v1 -->"
PENDING = "pending_sweep_reports"


def queue_report(ledger, repo: str, report: dict) -> None:
    pending = json.loads(ledger.get_cursor(repo, PENDING) or "[]")
    if not any(item.get("run_id") == report.get("run_id") for item in pending):
        pending.append(report)
    ledger.set_cursor(repo, PENDING, json.dumps(pending, sort_keys=True, default=str))


def flush_reports(rt, lifecycle) -> list[str]:
    """Publish every queued report; a failure keeps it (and the rest) queued."""
    pending = json.loads(rt.ledger.get_cursor(lifecycle.repo, PENDING) or "[]")
    done: list[str] = []
    while pending:
        publish_summary(rt, lifecycle, pending[0])
        done.append(str(pending[0].get("run_id")))
        pending = pending[1:]
        rt.ledger.set_cursor(lifecycle.repo, PENDING, json.dumps(pending, sort_keys=True, default=str))
    return done


def report_id(rt, report: dict) -> str:
    """Stable for one sweep (across its resumed attempts), distinct across
    sweeps: a release sweep is its tag; a periodic fallback sweep re-checks the
    same tag, so it also carries its start date."""
    import datetime as dt

    sweep = report["sweep"]
    tag = sweep.get("tag") or "untagged"
    if sweep.get("reason") == "release":
        return tag
    started = float(report.get("started_at") or rt.clock())
    return f"{tag}-{sweep.get('reason') or 'sweep'}-" \
           f"{dt.datetime.fromtimestamp(started, dt.timezone.utc).strftime('%Y%m%d')}"


def summary(rt, lifecycle, report: dict) -> tuple[str, str]:
    sweep = report["sweep"]
    tag = report_id(rt, report)
    t1 = report.get("t1") or {}
    statuses: Counter = Counter()
    ops: Counter = Counter()
    for changeset_id in report.get("changesets") or []:
        changeset = rt.ledger.changeset(changeset_id)
        statuses[changeset["status"]] += 1
        for op in changeset["detail"].get("operations") or []:
            ops[op["kind"]] += 1
    tokens = {"input": 0, "output": 0}
    seconds = 0.0
    calls = 0
    if getattr(rt, "traces", None) is not None and report.get("run_id"):
        run_id = report["run_id"]  # this sweep instance only (a fallback reuses the tag)
        for record in rt.traces.query(kind="model_call", run_id=run_id, limit=100000):
            calls += 1
            tokens["input"] += int((record.get("usage") or {}).get("input_tokens") or 0)
            tokens["output"] += int((record.get("usage") or {}).get("output_tokens") or 0)
            seconds += float(record.get("seconds") or 0)
    title = f"Knowledge sweep report: {lifecycle.repo} {tag}"
    lines = [
        MARKER,
        f"Release sweep of `{lifecycle.repo}` for **{tag}** "
        f"(`{str(sweep.get('from_sha') or '')[:12]}..{str(sweep.get('to_sha') or '')[:12]}`, "
        f"trigger: {sweep.get('reason', '')}).",
        "",
        "| | |", "|---|---|",
        f"| structural issues (T1) | {len(t1.get('issues') or [])} |",
        f"| duplicate rule IDs | {len(t1.get('duplicates') or {})} |",
        f"| pages over capacity | {len(t1.get('over_capacity') or {})} |",
        f"| pages missing from an index (fixed) | {len(t1.get('unlisted') or [])} |",
        f"| pages kept as they are | {len(report.get('kept_pages', report.get('skipped_pages')) or [])} |",
        f"| pages that failed an evaluation | {len(report.get('failed_attempts') or set(report.get('failed_pages') or []))} "
        f"({sum((report.get('failed_attempts') or {}).values())} failed attempts) |",
        f"| change sets | {sum(statuses.values())} "
        f"({', '.join(f'{k}: {v}' for k, v in sorted(statuses.items())) or 'none'}) |",
        f"| operations | {', '.join(f'{k}: {v}' for k, v in sorted(ops.items())) or 'none'} |",
        f"| waiting for people | {len(rt.ledger.human_queue(lifecycle.repo))} |",
        f"| release audit reconciliation findings | "
        f"{'not run' if report.get('reconciliation') is None else report['reconciliation']} |",
        f"| model calls | {calls} ({tokens['input']} in / {tokens['output']} out tokens, {seconds:.0f}s) |",
    ]
    if report.get("breaker"):
        lines += ["", f"**Circuit breaker:** {report['breaker']}; every change set went to people."]
    lines += ["", "Generated by the Copilot knowledge service."]
    return title, "\n".join(lines) + "\n"


def publish_summary(rt, lifecycle, report: dict) -> str:
    """Write the summary locally; open the issue only where publication is allowed."""
    title, body = summary(rt, lifecycle, report)
    path = rt.state_dir / "reports" / f"sweep-{lifecycle.repo}-{report_id(rt, report)}.md"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(f"# {title}\n\n{body}", encoding="utf-8")
    if rt.outbox is None or not lifecycle.auto_merge or not lifecycle.publishes:
        return "recorded"
    rt.outbox.issue(lifecycle.repo, "open_issue", {"title": title, "body": body, "labels": ["kb:sweep-report"]})
    return "issued"
